POST http://127.0.0.1:8000/auth/register/
Content-Type: application/json

{
    "username": "user1",
    "email": "fr3ew2@qejjyl.com",
    "password":"ayush@1234",
    "confirm_password":"ayush@1234"
}

###

POST http://127.0.0.1:8000/auth/verify-otp/
Content-Type: application/json

{
    "email": "fr3ew2@qejjyl.com",
    "otp": "633729"

}

###

POST http://127.0.0.1:8000/auth/resend-otp/
Content-Type: application/json

{
    "email": "nvl0t@vvatxiy.com"

}


###



POST http://127.0.0.1:8000/auth/login/
Content-Type: application/json

{
    "username":"user2",
    "password":"ayush@1234"
}

###

POST http://127.0.0.1:8000/healthcare/form/submit/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzMDA4NjAxLCJpYXQiOjE3NDI5MjIyMDEsImp0aSI6IjY1ZTllZTdjMDk4YzQ2NmNhNGJmOTI3NTcxOWNlOWM5IiwidXNlcl9pZCI6NH0.iVs2cFiNksybl1yS5a7vLOa7LKcU7fYUDEj-p_LUwGE

 {
    "name": "User1",
    "age": 6,
    "gender": "Female",
    "state": "Delhi",
    "contact_details": "9873443240",
    "chronic_conditions": "Arthritis, High Cholesterol",
    "past_surgeries": "Hip Replacement",
    "allergies": "Penicillin",
    "medications": "Atorvastatin, Ibuprofen",
    "symptoms": "Joint pain and stiffness",
    "symptom_severity": "Moderate",
    "symptom_duration": "Chronic",
    "mental_health_stress": false,
    "mental_health_anxiety": false,
    "mental_health_depression": false,
    "vaccination_history": "Covid-19, Pneumonia",
    "accessibility_needs": "Hearing aid support",
    "pregnancy_status": "Not Applicable",
    "emergency_contact": {
      "name": "Emma Green",
      "relationship": "Daughter",
      "number": "4376543241"
    },
    "health_insurance_provider": "WellCare",
    "health_insurance_policy": "MN123456",
    "preferred_language": "English",
    "research_participation": false
  }
###

GET http://127.0.0.1:8000/healthcare/form/me/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzMTQyNzExLCJpYXQiOjE3NDMwNTYzMTEsImp0aSI6ImIzOWNmNTc0MDYwZTQ0ZTA5M2E3ZWI1ZDg4YWQ4YjM5IiwidXNlcl9pZCI6NH0.hmo_k8RMBP8RKMc4eXMJyDM1cHyVYWzNul-VUfH4PM8


###

PATCH http://127.0.0.1:8000/healthcare/form/me/update/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzMDA3OTU1LCJpYXQiOjE3NDI5MjE1NTUsImp0aSI6IjFhOGNmY2M4ODgxMjQyYTc4MTFjNWRlMjdmMjg5ZDVjIiwidXNlcl9pZCI6M30.f0Z9loUE4Dxd6o1AsR0Fc4rmINPWWPlFSaFp8uNlmQ4

{
    "name":"User1"
}

###

GET http://127.0.0.1:8000/blogs/posts/
Content-Type: application/json


###

POST http://127.0.0.1:8000/blogs/posts/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzNjgxMDMwLCJpYXQiOjE3NDM1OTQ2MzAsImp0aSI6IjBjNjIyNTAxN2EyYjRlMWNhZGRlN2FhMDJmMDFlMDFhIiwidXNlcl9pZCI6M30.RJaAgbpaBHOiFe3-p9a-nuAbmku8AmOfHjwM67kUAPE

{
    "title": "My Second Blog Post by Admin",
    "content": "This is my first blog post. I am excited to share it with you"
}

###


DELETE http://127.0.0.1:8000/blogs/posts/8/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzNjgxMDMwLCJpYXQiOjE3NDM1OTQ2MzAsImp0aSI6IjBjNjIyNTAxN2EyYjRlMWNhZGRlN2FhMDJmMDFlMDFhIiwidXNlcl9pZCI6M30.RJaAgbpaBHOiFe3-p9a-nuAbmku8AmOfHjwM67kUAPE

