POST http://127.0.0.1:8000/auth/register/
Content-Type: application/json

{
    "username": "user6",
    "email": "nvl0t@vvatxiy.com",
    "password":"ayush@1234",
    "confirm_password":"ayush@1234"
}

###

POST http://127.0.0.1:8000/auth/verify-otp/
Content-Type: application/json

{
    "email": "nvl0t@vvatxiy.com",
    "otp": "260365"

}

###

POST http://127.0.0.1:8000/auth/resend-otp/
Content-Type: application/json

{
    "email": "nvl0t@vvatxiy.com"

}


###



POST http://127.0.0.1:8000/auth/login/
Content-Type: application/json

{
    "username":"user3",
    "password":"ayush@1234"
}

###

POST http://127.0.0.1:8000/healthcare/form/submit/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQyODM1MjA3LCJpYXQiOjE3NDI3NDg4MDcsImp0aSI6ImRmYzg4Mzc0MWU5ZjQzODA5OWE5MDlhMmY1MzJjODE5IiwidXNlcl9pZCI6Nn0.A7ISPsz8wqecCFJk8FrYSAQdsEfPm0rQ0hXK4G7g_ug

 {
    "name": "User4",
    "age": 60,
    "gender": "Male",
    "contact_details": "9876543240",
    "chronic_conditions": "Arthritis, High Cholesterol",
    "past_surgeries": "Hip Replacement",
    "allergies": "Penicillin",
    "medications": "Atorvastatin, Ibuprofen",
    "symptoms": "Joint pain and stiffness",
    "symptom_severity": "Moderate",
    "symptom_duration": "Chronic",
    "mental_health_stress": false,
    "mental_health_anxiety": false,
    "mental_health_depression": false,
    "vaccination_history": "Covid-19, Pneumonia",
    "accessibility_needs": "Hearing aid support",
    "pregnancy_status": "Not Applicable",
    "emergency_contact": {
      "name": "Emma Green",
      "relationship": "Daughter",
      "number": "4376543241"
    },
    "health_insurance_provider": "WellCare",
    "health_insurance_policy": "MN123456",
    "preferred_language": "English",
    "research_participation": false
  }
###

GET http://127.0.0.1:8000/healthcare/form/me/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQyOTEzNDk5LCJpYXQiOjE3NDI4MjcwOTksImp0aSI6ImU2NGVjZWU3ODQwMjQwOWJiMjI1MDkwMDQ1NTVhYWI5IiwidXNlcl9pZCI6NX0.-tgEdPQygCRzoYHW0yNDBbjusvbgM7z4-HUuA4qPpr4


###

PATCH http://127.0.0.1:8000/healthcare/form/me/update/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQyOTEzNDk5LCJpYXQiOjE3NDI4MjcwOTksImp0aSI6ImU2NGVjZWU3ODQwMjQwOWJiMjI1MDkwMDQ1NTVhYWI5IiwidXNlcl9pZCI6NX0.-tgEdPQygCRzoYHW0yNDBbjusvbgM7z4-HUuA4qPpr4

{
    "name":"User1"
}

###



